version: '3.4'

services:
  sulu:
    image: cse301-sulu-docker
    container_name: cse301-sulu-docker
    depends_on: 
      - database
    build: .
    ports:
      - 80:80

  database:
    image: mysql:5.7
    container_name: cse301-sulu-docker-database
    ports: 
      - 33066:3306
    environment: 
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
