CREATE DATABASE IF NOT EXISTS `MYSQL_DATABASE_sulu`;
USE `MYSQL_DATABASE_sulu`;

GRANT CREATE ROUTINE, CREATE VIEW, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, INSERT, SELECT, DELETE, TRIGGER, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON `MYSQL_DATABASE_sulu`.* TO 'MYSQL_USER'@'%';

