parameters:
    database_driver:    mysql
    database_host:     database
    database_port:     ~
    database_name:     sulu
    database_user:     root
    database_password: ~
    database_version:  5.5
    # You should uncomment this if you want use pdo_sqlite
    # database_path: "%kernel.root_dir%/data.db3"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    # A secret key that's used to generate certain security-related tokens
    secret:            ThisTokenIsNotSoSecretChangeIt

    sulu_admin.name:    Sulu
    sulu_admin.email:   ~

    websocket_port: 9876
    websocket_url: 'sulu.lo'
